"""transaction

Revision ID: e65abcb2c6dd
Revises: 5788348fe4bc
Create Date: 2024-04-15 23:34:30.393464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65abcb2c6dd'
down_revision: Union[str, None] = '5788348fe4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('amount_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_remarks', sa.String(), nullable=True),
    sa.Column('txn_time', sa.Time(), nullable=True),
    sa.Column('begin_balance', sa.Float(), nullable=True),
    sa.Column('end_balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
